apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  type: NodePort
  ports:
    - protocol: TCP
      port: 8501        # internal cluster port
      targetPort: 8501  # container port
      nodePort: 30001   # external port for access
